# -*- coding: utf-8 -*-
"""Cooking Recipe Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SwdZ-ndRhYSQm_DwQNHMNl4djNtFuaWr
"""

pip install gradio groq

# Bella
import subprocess
import sys

def install_packages():
    packages = ['gradio', 'groq']
    for package in packages:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", package])

install_packages()

import gradio as gr
from groq import Groq

# System prompt to restrict the chatbot to cooking topics only
SYSTEM_PROMPT = """You are a Cooking Expert Chatbot. Your ONLY purpose is to help users with cooking, food preparation, and culinary-related questions.

Your expertise includes:
- Recipes for various cuisines (Italian, Chinese, Indian, Mexican, French, etc.)
- Cooking techniques and methods (baking, grilling, sautéing, steaming, etc.)
- Ingredient substitutions and alternatives
- Kitchen equipment and tools
- Food preparation and meal planning
- Cooking tips and tricks
- Baking (bread, cakes, pastries, cookies)
- Dietary modifications (vegetarian, vegan, gluten-free, low-carb, etc.)
- Food safety and storage
- Knife skills and cutting techniques
- Seasoning and flavor combinations
- Cooking measurements and conversions
- Sauce and condiment preparation
- Meal prep and batch cooking
- Cooking for special occasions
- Troubleshooting cooking problems
- Plating and presentation
- Regional and international cuisines

STRICT RULES:
1. ONLY answer questions related to cooking, recipes, food preparation, and culinary topics
2. Provide clear, step-by-step instructions when giving recipes
3. Include measurements, cooking times, and temperatures when relevant
4. Suggest alternatives for dietary restrictions when asked
5. If a question is NOT about cooking or food, politely decline and redirect to cooking topics
6. Do NOT answer questions about: politics, technology, sports, entertainment, finance, etc.
7. Be helpful, encouraging, and make cooking accessible to all skill levels
8. When discussing food safety, provide accurate and important safety information

Response format for off-topic questions:
"I apologize, but I'm specifically designed to help with cooking and culinary questions only. I cannot assist with [topic]. However, I'd be happy to help you with recipes, cooking techniques, ingredient substitutions, meal planning, or any other cooking-related questions. What can I help you cook today?"
"""

# Global variables
groq_client = None

def set_api_key(api_key):
    """Initialize Groq client with API key"""
    global groq_client

    if not api_key or api_key.strip() == "":
        return "❌ Please enter a valid Groq API key"

    try:
        groq_client = Groq(api_key=api_key.strip())

        # Test the API key with a simple call
        test_response = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": "Hi"}],
            max_tokens=10
        )

        return "✅ API Key set successfully! You can now start cooking with me!"
    except Exception as e:
        groq_client = None
        return f"❌ Error setting API key: {str(e)}"

def respond(message, history):
    """Process chat messages and return response as a STRING"""
    global groq_client

    # Check if API key is set
    if groq_client is None:
        return "⚠️ Please enter your Groq API key and click 'Set API Key' button first."

    # Check if message is empty
    if not message or message.strip() == "":
        return "⚠️ Please enter a message."

    try:
        # Build messages list for API
        messages = [{"role": "system", "content": SYSTEM_PROMPT}]

        # Add conversation history
        if history:
            for msg in history:
                if isinstance(msg, dict) and "role" in msg and "content" in msg:
                    messages.append({
                        "role": msg["role"],
                        "content": msg["content"]
                    })

        # Add current user message
        messages.append({
            "role": "user",
            "content": message
        })

        # Call Groq API
        completion = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=messages,
            temperature=0.7,
            max_tokens=2048,
            stream=False
        )

        # Extract and return the response text
        response_text = completion.choices[0].message.content

        return str(response_text)

    except Exception as e:
        error_message = f"❌ Error: {str(e)}\n\nPlease check your API key and try again."
        return str(error_message)

# Create Gradio interface
with gr.Blocks(title="Cooking Chatbot", theme=gr.themes.Soft()) as demo:
    gr.Markdown(
        """
        # 👨‍🍳 Cooking Chatbot
        ### Your Personal Culinary Assistant

        Ask me anything about cooking! Get recipes, cooking tips, ingredient substitutions,
        technique guidance, and more. From beginner basics to advanced culinary techniques!

        **Note:** This chatbot only answers cooking and food preparation questions.
        """
    )

    with gr.Row():
        with gr.Column(scale=3):
            api_key_input = gr.Textbox(
                label="🔑 Groq API Key",
                placeholder="Enter your Groq API key here...",
                type="password"
            )
        with gr.Column(scale=1):
            set_key_btn = gr.Button("Set API Key", variant="primary", size="lg")

    api_status = gr.Textbox(label="Status", interactive=False)

    gr.Markdown("--- ")

    # Create ChatInterface
    chat_interface = gr.ChatInterface(
        fn=respond,
        type="messages",
        chatbot=gr.Chatbot(
            height=450,
            type="messages",
            label="Chat"
        ),
        textbox=gr.Textbox(
            placeholder="Ask me about recipes, cooking techniques, ingredients...",
            label="Your Cooking Question"
        ),
        examples=[
            "How do I make a perfect scrambled eggs?",
            "Give me a recipe for chocolate chip cookies",
            "What can I substitute for eggs in baking?",
            "How do I cook pasta perfectly?",
            "What's a good marinade for chicken?",
            "How do I make homemade pizza dough?",
            "What are the basic knife skills I should learn?",
            "How do I make a simple tomato sauce?",
            "What's the difference between baking soda and baking powder?",
            "Give me a vegetarian lasagna recipe",
            "How do I properly season a cast iron skillet?",
            "What temperature should I cook salmon to?",
        ],
        cache_examples=False
    )

    # Connect the Set API Key button
    set_key_btn.click(
        fn=set_api_key,
        inputs=[api_key_input],
        outputs=[api_status]
    )

    gr.Markdown(
        """
        ---
        ### 📝 Instructions:
        1. **Get your Groq API key**: Visit https://console.groq.com/keys
        2. **Enter the API key** in the field above and click "Set API Key"
        3. **Wait for success message** (✅ API Key set successfully!)
        4. **Start asking** cooking questions

        ### 🍳 What I Can Help You With:
        - **Recipes**: Get detailed recipes for any dish or cuisine
        - **Cooking Techniques**: Learn how to sauté, braise, roast, and more
        - **Ingredient Substitutions**: Find alternatives for dietary needs
        - **Meal Planning**: Plan your weekly meals
        - **Baking**: Master breads, cakes, pastries, and desserts
        - **Food Safety**: Learn proper storage and handling
        - **Kitchen Skills**: Improve your knife work and cooking methods
        - **Dietary Modifications**: Adapt recipes for vegan, gluten-free, etc.
        - **Troubleshooting**: Fix cooking mistakes and problems
        - **International Cuisines**: Explore flavors from around the world

        ### 🍽️ Tips for Best Results:
        - Be specific about serving sizes (e.g., "recipe for 4 people")
        - Mention dietary restrictions upfront
        - Ask follow-up questions for clarification
        - Request step-by-step instructions if needed

        ### ⚠️ Food Safety Reminder:
        Always follow proper food safety guidelines including proper cooking temperatures,
        food storage, and hygiene practices to ensure safe and delicious meals!
        """
    )

# Launch the app
if __name__ == "__main__":
    demo.launch(share=True)